Update/avnm secured hub and spoke
mspnp/samples pull request #241
Opened 2024-06-25 10:27 UTC by v-fearam

rg naming
rg location as default location to create resources

2025-02-28 14:40 UTC, ferantivero requested changes
nice work @v-fearam, please let's go ahead a review the requested and suggested changes.

2025-02-28 16:10 UTC, ckittel commented on solutions/avnm-secured-hub-and-spoke/README.md
> -az deployment group create \
I think the arm templates are currently used in "samples browser" @ https://learn.microsoft.com/en-us/samples/mspnp/samples/virtual-network-manager-secured-hub-and-spoke/

2025-02-28 17:42 UTC, ferantivero commented on solutions/avnm-secured-hub-and-spoke/README.md
> -az deployment group create \
well spotted @ckittel, my expectation is that as soon as we update the README here the "samples browser" gets updated as well.

Is that assumption wrong? 

Regarding getting them in sync I think @v-fearam can help on this a bit.

2025-02-28 17:43 UTC, ferantivero commented
Please let me use a bit more of your time since we've got your attention @ckittel in here. Something I found a bit odd is the new sec parts we are incorporating from this PR that looks like scope creep for an sample. 

Thoughts?

2025-02-28 17:47 UTC, ckittel commented on solutions/avnm-secured-hub-and-spoke/README.md
> -az deployment group create \
Yup, updates here will update the samples browser.  We also had it as JSON because there used to be a Azure Portal experience around these assets.  Meaning you could click a button IN the Azure Portal and the json from these repos were brought into the Azure Deploy UI flow.  That process is no longer there, so I think it's safe to remove the json.

2025-02-28 18:04 UTC, ferantivero commented on solutions/avnm-secured-hub-and-spoke/README.md
> -az deployment group create \
now I got you!

2025-02-28 19:52 UTC, ferantivero requested changes
please let me land a new quick review @v-fearam

2025-02-28 19:52 UTC, ferantivero commented on solutions/avnm-secured-hub-and-spoke/bicep/modules/spoke.bicep
> +resource recoveryServicesVault 'Microsoft.RecoveryServices/vaults@2021-08-01' = {
please let's remove recovery vault

2025-02-28 19:52 UTC, ferantivero commented on solutions/avnm-secured-hub-and-spoke/bicep/modules/spoke.bicep
> +        name: 'DenyInternetAccess'
```suggestion
        name: 'DenyInboundInternet'
```

2025-02-28 19:52 UTC, ferantivero commented on solutions/avnm-secured-hub-and-spoke/bicep/modules/spoke.bicep
> +          patchMode: 'AutomaticByPlatform '
```suggestion
          patchMode: 'AutomaticByPlatform'
```

2025-03-05 18:12 UTC, v-fearam commented on solutions/avnm-secured-hub-and-spoke/bicep/modules/spoke.bicep
> +    type: 'SystemAssigned'
done

2025-03-07 18:52 UTC, v-fearam commented on solutions/avnm-secured-hub-and-spoke/README.md
> -az deployment group create \
After reviewing the files and the connected Bicep files, I propose the following changes in a new pull request:
* update the API versions
* Standardize the naming conventions
* Incorporate the following improvements:
   *  Implement zone redundancy where possible, with only one zone enabled.
   *  Add monitoring and configure diagnostic settings when applicable.
   *  Include a basic firewall deployment in the hub  

I'm open to further suggestions on other improvements.

2025-03-07 18:52 UTC, v-fearam commented on solutions/avnm-secured-hub-and-spoke/README.md
> +LOCATION=eastus
done

2025-03-07 20:54 UTC, ferantivero commented on solutions/avnm-secured-hub-and-spoke/README.md
> +az feature register --namespace "Microsoft.Compute" --name "EncryptionAtHost"
it is safe to remove encryption at host as well and then remove step1 just hardcoding the name of hub rg where required.

2025-03-10 13:23 UTC, ferantivero commented on solutions/avnm-secured-hub-and-spoke/README.md
> +| `sshkey`        | string       | The user's public SSH key to be added to the Linux machines as part of the `ssh_authorized_keys` list    |                  |
it seems we missed to add the resourcegroup param

2025-03-10 13:43 UTC, v-fearam commented on solutions/avnm-secured-hub-and-spoke/README.md
> +| `sshkey`        | string       | Your public key. Authentication to Linux machines should require SSH keys  |                  |
done

2025-03-10 13:44 UTC, v-fearam commented on solutions/avnm-secured-hub-and-spoke/bicep/modules/spoke.bicep
> +// Guest Configuration extension should be installed using the system-assigned managed identity
done

2025-03-10 13:44 UTC, v-fearam commented on solutions/avnm-secured-hub-and-spoke/bicep/modules/spoke.bicep
> +// Non-internet-facing virtual machines should be protected with network security groups
done

2025-03-10 13:44 UTC, v-fearam commented on solutions/avnm-secured-hub-and-spoke/bicep/modules/spoke.bicep
> +@description('Install the Guest Configuration extension for auditing purposes on the VM.')
done

2025-03-10 13:44 UTC, v-fearam commented on solutions/avnm-secured-hub-and-spoke/bicep/modules/spoke.bicep
> +resource recoveryServicesVault 'Microsoft.RecoveryServices/vaults@2021-08-01' = {
done

2025-03-10 13:44 UTC, v-fearam commented on solutions/avnm-secured-hub-and-spoke/bicep/modules/spoke.bicep
> +        name: 'DenyInternetAccess'
done

2025-03-10 13:44 UTC, v-fearam commented on solutions/avnm-secured-hub-and-spoke/bicep/modules/spoke.bicep
> +          patchMode: 'AutomaticByPlatform '
done

2025-03-10 14:00 UTC, ferantivero commented on solutions/avnm-secured-hub-and-spoke/bicep/main.bicep
> +param location string = deployment().location
can we please test deploying to westus instead?

2025-03-10 14:28 UTC, ferantivero commented on solutions/avnm-secured-hub-and-spoke/README.md
> -az deployment group create \
I will keep this one open until you create the new PR for this @v-fearam

2025-03-10 20:13 UTC, ferantivero commented on solutions/avnm-secured-hub-and-spoke/README.md
> +| `location`      | string       | Deployment location                   | `resourceGroup().location` |
it seems the default is not the resource group location but the deployment.

If we decide to go with existent instead of creating, can we explore the idea of removing this param from bicep?

2025-03-11 16:16 UTC, v-fearam commented on solutions/avnm-secured-hub-and-spoke/bicep/modules/spoke.bicep
> +          access: 'Deny'
Security admin rules and network security groups (NSGs) can be used to enforce network security policies in Azure. However, they have different scopes and priorities.#

Security admin rules are intended to be used by network admins of a central governance team. This allows individual application or service teams to further specify security as needed with NSGs. Security admin rules have a higher priority than NSGs and are evaluated before NSG rules.
[more information](https://learn.microsoft.com/azure/virtual-network-manager/concept-security-admins#how-security-admin-rules-and-network-security-groups-nsgs-are-evaluated).  

Anyway, I deleted the NSG, it is not adding value in the current implementation.

2025-03-11 16:18 UTC, v-fearam commented on solutions/avnm-secured-hub-and-spoke/bicep/main.bicep
> +param location string = deployment().location
The main bicep is at subscription level because of policy creation. I decided to create the resource group inside the bicep file to avoid conflicts detected (good cacth). The location is taken from the deployment location for the resource group and all the resources are in the resource group location. The name of the resource group contains the suffix -location.

I changed the EncriptionAtHost to false as requested. 

The readme was updated accordingly

2025-03-11 17:00 UTC, v-fearam commented on solutions/avnm-secured-hub-and-spoke/README.md
> +| `location`      | string       | Deployment location                   | `resourceGroup().location` |
Location was removed as parameter, the same for resource group name.

2025-03-11 17:00 UTC, v-fearam commented on solutions/avnm-secured-hub-and-spoke/README.md
> +| `sshkey`        | string       | The user's public SSH key to be added to the Linux machines as part of the `ssh_authorized_keys` list    |                  |
Location was removed as parameter, the same for resource group name.

2025-03-11 17:01 UTC, v-fearam commented
It was tested the dynamic group for spoke VNETs.


![image](https://github.com/user-attachments/assets/1d9794a6-d152-4d76-9dc7-4ea224088937)


Deploy end to end after all changes worked.

az deployment sub create --location eastus --template-file main.bicep -n avnm-secured-hub-and-spoke --parameters sshKey="$(cat ~/.ssh/id_rsa.pub)"
![image](https://github.com/user-attachments/assets/85c1896c-34f5-465d-8dcb-1e4aa01d7a98)

2025-03-11 17:03 UTC, ferantivero commented on solutions/avnm-secured-hub-and-spoke/bicep/main.bicep
> +  name:  resourceGroupName
```suggestion
  name: resourceGroupName
```

2025-03-11 17:10 UTC, ferantivero commented on solutions/avnm-secured-hub-and-spoke/README.md
> +| `sshkey`        | string       | The user's public SSH key to be added to the Linux machines as part of the `ssh_authorized_keys` list    |                  |
@ckittel we're creating the rg as part of the subs deployment. Currently hardcoding its name within the bicep, so we are considering removing the param for this.

Are you up for this removal or keeping it as part of the params is desired?

2025-03-11 17:32 UTC, ferantivero commented on solutions/avnm-secured-hub-and-spoke/README.md
> +| `sshkey`        | string       | The user's public SSH key to be added to the Linux machines as part of the `ssh_authorized_keys` list    |                  |
alright, marking this as resolved for now

2025-03-11 18:07 UTC, merged

2025-06-05 16:10 UTC, ferantivero commented on solutions/avnm-secured-hub-and-spoke/README.md
> -az deployment group create \
[PR](https://github.com/mspnp/samples/pull/250) is now created, so marking this as resolved