update/secure-hybrid-network
mspnp/samples pull request #245
Opened 2024-07-04 16:37 UTC by v-fearam

RG name
Using bicep
clean up
Changing resource location 
making the script work

2025-03-17 12:38 UTC, v-fearam commented on solutions/secure-hybrid-network/nestedtemplates/azure-network-azuredeploy.bicep
> +    publicIPAllocationMethod: 'Static'
Standard sku publicIp /subscriptions/9c257b18-344d-4d4b-b09e-5c0a80b50e48/resourceGroups/rg-site-to-site-mock-prem-eastus2/providers/Microsoft.Network/publicIPAddresses/pip-onprem-vpn-gateway must have AllocationMethod set to Static. (Code: StandardSkuPublicIPAddressesMustBeStatic)

2025-03-17 12:42 UTC, v-fearam commented on solutions/secure-hybrid-network/nestedtemplates/mock-onprem-azuredeploy.bicep
> +    publicIPAllocationMethod: 'Static'
Standard sku publicIp /subscriptions/9c257b18-344d-4d4b-b09e-5c0a80b50e48/resourceGroups/rg-site-to-site-mock-prem-eastus2/providers/Microsoft.Network/publicIPAddresses/pip-onprem-vpn-gateway must have AllocationMethod set to Static. (Code: StandardSkuPublicIPAddressesMustBeStatic)

2025-04-03 17:44 UTC, v-fearam commented on solutions/secure-hybrid-network/README.md
> +| vmSize | string | Size of the load-balanced virtual machines. | Standard_DS1_v2 |
We used D series because the following:

The selected VM size 'Standard_A4_v2' cannot boot Hypervisor Generation '2'. If this was a Create operation please check that the Hypervisor Generation of the Image matches the Hypervisor Generation of the selected VM Size.

2025-04-07 15:01 UTC, ferantivero requested changes
great edits @v-fearam, a few requested changes below

2025-04-09 16:11 UTC, v-federicoar commented on solutions/secure-hybrid-network/README.md
> +| vmSize | string | Size of the load-balanced virtual machines. | Standard_DS1_v2 |
You were right, thank for the comment. I was back that change and I was moved to Standard_A4_v2

2025-04-09 16:11 UTC, v-federicoar commented on solutions/secure-hybrid-network/README.md
> +| vmSize | string | Size of the load-balanced virtual machines. | Standard_DS1_v2 |
moved to Standard_A4_v2

2025-04-09 16:12 UTC, v-federicoar commented on solutions/secure-hybrid-network/nestedtemplates/azure-network-azuredeploy.bicep
> +var windowsOSVersion = '2022-datacenter-g2'
It was rollbacked

2025-04-09 18:40 UTC, v-federicoar commented on solutions/secure-hybrid-network/azuredeploy.bicep
>  resource mocOnPremResourceGroup_resource 'Microsoft.Resources/resourceGroups@2022-09-01' = {
done

2025-04-10 16:44 UTC, ferantivero approved these changes
nice work @v-fearam! LGTM 🚀

2025-04-10 17:43 UTC, merged